# Generated by Django 5.0.3 on 2024-03-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0002_remove_cookbook_author_remove_cookbook_recipes"),
        ("recipe", "0002_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cookbook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="cookbook.cookbook",
            ),
        ),
    ]
