# Generated by Django 5.0.3 on 2024-03-20 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_remove_recipe_cookbook_recipe_recipes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="recipes",
        ),
    ]
